language: go
go:
    - 1.5
    - 1.6
    - tip

go_import_path: go.mozilla.org/mozldap

matrix:
    fast_finish: true

before_install:
    - go get github.com/golang/lint/golint

script:
    # make sure it builds
    - make vet lint generate test install
    # test if deps are up to date
    - govend -u && git diff --quiet
